full_filepaths <- list.files("rawdata", full.names = TRUE)
print(full_filepaths)
outcome <- read.csv(full_filepaths[2], colClasses = "character")
print(head(outcome))
print(ncol(outcome))
print(names(outcome))
outcome[ , 11] <- as.numeric(outcome[ , 11])
print(head(outcome[ , 11]))
hist(outcome[ , 11])